sudo: required
services:
  - docker

before_install:
  - docker build -t mikemcgarry/view-test -f ./view/Dockerfile.dev ./view

script:
  - docker run mikemcgarry/view-test npm test -- --coverage

after_success:
  - docker build -t mikemcgarry/gym-hero-view ./view
  - docker build -t mikemcgarry/gym-hero-controller ./controller
  - docker build -t mikemcgarry/gym-hero-server ./server

  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push mikemcgarry/gym-hero-view
  - docker push mikemcgarry/gym-hero-controller
  - docker push mikemcgarry/gym-hero-server

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: gym-hero
  env: GymHero-env-1
  bucket_name: elasticbeanstalk-eu-west-2-705284077756
  bucket_path: gym-hero
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: $AWS_ACCESS_KEY_SECRET
