sudo: required

services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - openssl aes-256-cbc -K $encrypted_fd808f087d32_key -iv $encrypted_fd808f087d32_iv -in gym-hero-results-eab8406ed535.json.enc -out gym-hero-results-eab8406ed535.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file gym-hero-results-eab8406ed535.json
  - gcloud config set project gym-hero-results
  - gcloud config set compute/zone europe-west2-a
  - gcloud container clusters get-credentials gym-hero-cluster
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t mikemcgarry/view-test -f ./view/Dockerfile.dev ./view

script:
  - docker run mikemcgarry/view-test npm test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
