apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: gym-progress-com-tls
spec:
  secretName: gym-progress-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: gym-progress.com
  dnsNames:
    - gym-progress.com
    - www.gym-progress.com
