apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-deployment
spec:
  # Number of pods to create and manage
  replicas: 1
  # Allows deployment to get handle on created pods
  selector:
    matchLabels:
      component: api
  # The pod configurationm same as in a Pod config file
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: controller
          image: mikemcgarry/gym-hero-controller
          volumeMounts:
            - name: workoutdata
              mountPath: /tmp/controller/python-flask-app/data
          ports:
            - containerPort: 5000
        - name: datasource
          image: mikemcgarry/gym-hero-datasource
          volumeMounts:
            - name: workoutdata
              mountPath: /tmp/datasource/data
          env:
            - name: GYM_HERO_USERNAME
              value: mikejmcgarry
            - name: GYM_HERO_APP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gymhero.tokens
                  key: APP_TOKEN
      volumes:
        - name: workoutdata
          emptyDir: {}
