apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    kubernetes.io/ingress.global-static-ip-name: "gym-hero-ingress"
spec:
  rules:
    - http:
        paths:
          - path: /(.*)
            backend:
              serviceName: view-clusterip-service
              servicePort: 3000
          - path: /api/(.*)
            backend:
              serviceName: controller-clusterip-service
              servicePort: 5000
